# Generated by Django 3.0.7 on 2020-06-18 05:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_logo', models.FileField(upload_to='')),
                ('company_email', models.EmailField(max_length=50)),
                ('company_password', models.CharField(max_length=50)),
                ('company_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('company_address', models.CharField(max_length=200)),
                ('company_post_code', models.CharField(max_length=200)),
                ('company_country', models.CharField(max_length=200)),
                ('company_state', models.CharField(max_length=200)),
            ],
        ),
    ]
