# Generated by Django 3.0.7 on 2020-06-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_qrscanmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='qrscanmember',
            name='contact_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='qrscanmember',
            name='temperature',
            field=models.CharField(max_length=50),
        ),
    ]
