# Generated by Django 3.0.7 on 2020-06-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200622_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrscanmember',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='qrscanmember',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='qrscanmember',
            name='purpose_of_visitation',
        ),
    ]
