# Generated by Django 3.0.7 on 2020-06-23 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200623_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrscanmember',
            name='date_stamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrscanmember',
            name='time_stamp',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
