# Generated by Django 3.0.7 on 2020-06-23 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200623_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrscanmember',
            name='contact_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must not consist of space eg : +0123456789', regex='^(\\d{1,3})?,?\\s?\\d{8,13}')]),
        ),
    ]
