# Generated by Django 3.0.7 on 2020-06-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200623_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrscanmember',
            name='contact_number',
            field=models.CharField(max_length=50),
        ),
    ]
