# Generated by Django 3.0.7 on 2020-06-23 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200623_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrscanmember',
            name='temperature',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(40)]),
        ),
    ]
