# Generated by Django 3.0.7 on 2020-06-23 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200623_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrscanmember',
            name='contact_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must not consist of space and requires country code. eg : +6591258565', regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}$')]),
        ),
    ]
